variable "location" {}
variable "vnet_name" {}
variable "resource_group_name" {}
variable "container_name" {}
variable "storage_account_name" {}
variable "access_key" {}
variable "address-space" {}
variable "pub_sub_1_a_prefixes" {}
variable "pub_sub_2_b_prefixes" {}
variable "pri_sub_3_a_prefixes" {}
variable "pri_sub_4_b_prefixes" {}
variable "pri_sub_5_a_prefixes" {}
variable "pri_sub_6_b_prefixes" {}
